name: Push Image to GHCR and Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/yusufbahtiarr/fgo24-be-tickitz:latest

      - name: Copy migrations and data to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: "migrations,dmlsql"
          target: "/home/yusuf/deploy"

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd /home/yusuf/deploy

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/yusufbahtiarr/fgo24-be-tickitz:latest

            docker compose up -d postgres redis

            sleep 10

            docker run --rm \
              --network deploy_netapp \
              -v "$PWD/migrations:/migrations" \
              migrate/migrate \
              -path=/migrations \
              -database "postgres://postgres:1@postgres:5432/postgres?sslmode=disable" up

            # docker exec -i deploy-postgres-1 psql -U postgres -d postgres < dmlsql/dml.sql

            docker compose up -d --build app
