name: Push Image to GHCR and Deploy to VPS
run-name: Release Image to GHCR and Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Copy migrations to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: "migrations"
          target: "/home/${{ secrets.VPS_USER }}/deploy"

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/deploy
            docker pull ghcr.io/${{ github.repository }}:latest
            docker compose up -d postgres redis
            docker run --rm 
              --network deploy_netapp 
              -v "$PWD/migrations:/migrations" 
              migrate/migrate 
              -path=/migrations 
              -database "postgres://postgres:1@postgres:5432/postgres?sslmode=disable" up
            docker compose up -d --build app
